# Generated by Django 2.1 on 2018-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pineapple', '0002_auto_20180819_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='index',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
